[package]
name = "ifaddrsx"
version = "0.1.0"
edition = "2021"

[lib]
name = "ifaddrsx"
path = "src/lib.rs"

[features]
default = []
full = ["friendly", "mac"]
friendly = []
mac = ["nix"]

[dependencies]
ipnetwork = "0.18.0"
get_if_addrs = "0.5.3"
libc = "0.2.122"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["minwindef", "winerror", "ifdef", "ws2def", "ws2ipdef"] }

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "freebsd"))'.dependencies]
nix = { version = "0.23.1", optional = true }
